### ISSUE TITLE
Feed-me integration broken

### ISSUE THREAD

**Issue by WHITE-developer** [verbb/hyper#169]
### Describe the bug

Twig\Error\RuntimeError: Variable "path" does not exist. in` /var/www/html/vendor/verbb/hyper/src/templates/_integrations/feed-me/field.html:25`
Stack trace:
```
#0 /var/www/html/storage/runtime/compiled_templates/17/1701b9d899c38b180fb4cb864ed23c4f.php(64): __TwigTemplate_9b8567969f4d2841a52957e6045ff0a0->{closure}()
#1 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_9b8567969f4d2841a52957e6045ff0a0->doDisplay(Array, Array)
#2 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#3 /var/www/html/storage/runtime/compiled_templates/3c/3c9087d6c3542f59b45c18ca19fa3d53.php(231): Twig\Template->display(Array)
#4 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_d5d86cbb107b27fa9c24977a9de8e641->doDisplay(Array, Array)
#5 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#6 /var/www/html/storage/runtime/compiled_templates/a8/a83dac2fe7a07f1ab5acbb6620eccd91.php(169): Twig\Template->display(Array)
#7 /var/www/html/vendor/twig/twig/src/Template.php(171): __TwigTemplate_4825e52fc072658cfd94e19693ad030d->block_content(Array, Array)
#8 /var/www/html/storage/runtime/compiled_templates/52/5273c46110472657efad04ed19563271.php(642): Twig\Template->displayBlock('content', Array, Array)
#9 /var/www/html/vendor/twig/twig/src/Template.php(171): __TwigTemplate_4447b76364331c7ad00c0b31fd71b69d->block_main(Array, Array)
#10 /var/www/html/storage/runtime/compiled_templates/52/5273c46110472657efad04ed19563271.php(390): Twig\Template->displayBlock('main', Array, Array)
#11 /var/www/html/vendor/twig/twig/src/Template.php(171): __TwigTemplate_4447b76364331c7ad00c0b31fd71b69d->block_body(Array, Array)
#12 /var/www/html/storage/runtime/compiled_templates/ce/ce4f7ae2bb694977d08c1ce1572d27da.php(97): Twig\Template->displayBlock('body', Array, Array)
#13 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_616e7aab5d739f56f41c7df2d7f786e1->doDisplay(Array, Array)
#14 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#15 /var/www/html/storage/runtime/compiled_templates/6f/6f0b5a26b701ef91b279bc74b850ef00.php(56): Twig\Template->display(Array, Array)
#16 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_068f458c13d75cce50e22e5eee8d5781->doDisplay(Array, Array)
#17 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#18 /var/www/html/storage/runtime/compiled_templates/52/5273c46110472657efad04ed19563271.php(170): Twig\Template->display(Array, Array)
#19 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_4447b76364331c7ad00c0b31fd71b69d->doDisplay(Array, Array)
#20 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#21 /var/www/html/storage/runtime/compiled_templates/0c/0c1f49d88000323c11a1ae27d9a734da.php(57): Twig\Template->display(Array, Array)
#22 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_c85d0613552d7defcef75a93887f09ae->doDisplay(Array, Array)
#23 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#24 /var/www/html/storage/runtime/compiled_templates/a8/a83dac2fe7a07f1ab5acbb6620eccd91.php(79): Twig\Template->display(Array, Array)
#25 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_4825e52fc072658cfd94e19693ad030d->doDisplay(Array, Array)
#26 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#27 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#28 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(38): Twig\Template->render(Array)
#29 /var/www/html/vendor/twig/twig/src/Environment.php(280): Twig\TemplateWrapper->render(Array)
#30 /var/www/html/vendor/craftcms/cms/src/web/View.php(482): Twig\Environment->render('feed-me/feeds/_...', Array)
#31 /var/www/html/vendor/craftcms/cms/src/web/View.php(535): craft\web\View->renderTemplate('feed-me/feeds/_...', Array)
#32 /var/www/html/vendor/craftcms/cms/src/web/TemplateResponseFormatter.php(57): craft\web\View->renderPageTemplate('feed-me/feeds/_...', Array, 'cp')
#33 /var/www/html/vendor/yiisoft/yii2/web/Response.php(1109): craft\web\TemplateResponseFormatter->format(Object(craft\web\Response))
#34 /var/www/html/vendor/craftcms/cms/src/web/Response.php(338): yii\web\Response->prepare()
#35 /var/www/html/vendor/yiisoft/yii2/web/Response.php(340): craft\web\Response->prepare()
#36 /var/www/html/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#37 /var/www/html/web/index.php(12): yii\base\Application->run()
#38 {main}
```

### Steps to reproduce

1. Have an entry with hyper
2. Try creating a feed-me for that entry section
3. Crash on "map" page

### Craft CMS version

5.2.0-beta.5

### Plugin version

2.0.1

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed in [2.0.2](https://github.com/verbb/hyper/releases/tag/2.0.2)
