### ISSUE TITLE
Linkit 'Migrate Content' issue

### ISSUE THREAD

**Issue by iamtompickering** [verbb/hyper#220]
### Describe the bug

I'm trying to migrate my Linkit field content, and when I run it from the settings of Hyper, I get the following error logs

```
Preparing to migrate field “linksTo16” (ab532f4b-6a48-4218-9006-82b150189f06) content.
Exception: Invalid JSON data. (/Users/path/to/project/craft-3/vendor/yiisoft/yii2/helpers/BaseJson.php:123)
#0 /Users/path/to/project/craft-3/vendor/verbb/hyper/src/migrations/PluginContentMigration.php(77): yii\helpers\BaseJson::decode(Array)
#1 /Users/path/to/project/craft-3/vendor/verbb/hyper/src/migrations/PluginContentMigration.php(42): verbb\hyper\migrations\PluginContentMigration->processFieldContent()
#2 /Users/path/to/project/craft-3/vendor/craftcms/cms/src/db/Migration.php(50): verbb\hyper\migrations\PluginContentMigration->safeUp()
#3 /Users/path/to/project/craft-3/vendor/verbb/hyper/src/controllers/MigrationsController.php(77): craft\db\Migration->up()
#4 /Users/path/to/project/craft-3/vendor/verbb/hyper/src/controllers/MigrationsController.php(31): verbb\hyper\controllers\MigrationsController->_migrate('verbb\\hyper\\mig...')
#5 [internal function]: verbb\hyper\controllers\MigrationsController->actionLinkitContent()
#6 /Users/path/to/project/craft-3/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 /Users/path/to/project/craft-3/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#8 /Users/path/to/project/craft-3/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('linkit-content', Array)
#9 /Users/path/to/project/craft-3/vendor/craftcms/cms/src/web/Application.php(350): yii\base\Module->runAction('hyper/migration...', Array)
#10 /Users/path/to/project/craft-3/vendor/craftcms/cms/src/web/Application.php(649): craft\web\Application->runAction('hyper/migration...', Array)
#11 /Users/path/to/project/craft-3/vendor/craftcms/cms/src/web/Application.php(312): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#12 /Users/path/to/project/craft-3/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#13 /Users/path/to/project/craft-3/web/index.php(12): yii\base\Application->run()
#14 /Users/user/.composer/vendor/laravel/valet/server.php(110): require('/Users/tompicke...')
#15 {main}
```

Any ideas how to resolve this issue? One thing to note is that I did run through Crafts auto-merge command prior to this, so it is likely that this field was affected by that. Just thought it would be worth mentioning as I haven't really done anything else to the site since upgrading to Craft 5. 

### Steps to reproduce

1. Run Linkit Migrate Content

### Craft CMS version

5.5.5

### Plugin version

2.2.1

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/hyper:"dev-craft-5 as 2.2.1"`.

**Comment by iamtompickering** [comment]
Cheers @engram-design!
