### ISSUE TITLE
Creating new field is impossible to save, results in PHP error

### ISSUE THREAD

**Issue by davidwebca** [verbb/hyper#29]
### Describe the bug

Creating a new field and setting it to "Hyper" without changing any other detail results in a PHP error.

### Steps to reproduce

1. Add a new field and call it whatever
2. Select "Hyper" as the field type
3. Save the field and notice the following error.

```
craft\models\FieldLayout::createFromConfig(): Argument #1 ($config) must be of type array, null given, called in /vendor/verbb/hyper/src/fields/HyperField.php on line 639
```

### Craft CMS version

4.3.10

### Plugin version

1.0.5

### Multi-site?

Yes

### Additional context

Multi-site has two sites to handle English and German languages. Creating a field to any other type and then changing it to Hyper type does work, so that's the workaround I'm using right now. PHP version is 8.1.0.

**Comment by engram-design** [comment]
I believe that should already be fixed in [1.0.5.2](https://github.com/verbb/hyper/releases/tag/1.0.5.2) - but let me know if not?

**Comment by corneliusio** [comment]
We are also having this/similar issue. Just set up a new project and as soon as I save a new field as a Hyper field I get an error across the entire site, public and dashboard.

Craft Version: 4.3.10
Hyper Version: 1.0.5.2
Multisite: No

```
Error: Typed static property verbb\hyper\Hyper::$plugin must not be accessed before initialization in /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/verbb/hyper/src/fields/HyperField.php:395
Stack trace:
#0 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/yiisoft/yii2/base/Component.php(180): verbb\hyper\fields\HyperField->setLinkTypes(Array)
#1 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set('linkTypes', Array)
#2 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(verbb\hyper\fields\HyperField), Array)
#3 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/craftcms/cms/src/base/Model.php(78): yii\base\BaseObject->__construct(Array)
#4 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/verbb/hyper/src/fields/HyperField.php(73): craft\base\Model->__construct(Array)
#5 [internal function]: verbb\hyper\fields\HyperField->__construct(Array)
#6 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#7 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('verbb\\hyper\\fie...', Array, Array)
#8 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('verbb\\hyper\\fie...', Array, Array)
#9 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/craftcms/cms/src/Craft.php(53): yii\BaseYii::createObject(Array, Array)
#10 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/craftcms/cms/src/helpers/Component.php(122): Craft::createObject(Array)
#11 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/craftcms/cms/src/services/Fields.php(593): craft\helpers\Component::createComponent(Array, 'craft\\base\\Fiel...')
#12 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/craftcms/cms/src/services/Fields.php(618): craft\services\Fields->createField(Array)
#13 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/craftcms/cms/src/services/Fields.php(647): craft\services\Fields->_fields(NULL)
#14 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/craftcms/cms/src/elements/db/ElementQuery.php(2001): craft\services\Fields->getAllFields()
#15 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1315): craft\elements\db\ElementQuery->customFields()
#16 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#17 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build(Object(craft\elements\db\UserQuery))
#18 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/yiisoft/yii2/db/Query.php(287): yii\db\Query->createCommand(Object(craft\db\Connection))
#19 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/craftcms/cms/src/db/Query.php(275): yii\db\Query->one(NULL)
#20 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1506): craft\db\Query->one(NULL)
#21 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/craftcms/cms/src/elements/User.php(527): craft\elements\db\ElementQuery->one()
#22 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/yiisoft/yii2/web/User.php(698): craft\elements\User::findIdentity(1)
#23 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/craftcms/cms/src/web/User.php(500): yii\web\User->renewAuthStatus()
#24 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/yiisoft/yii2/web/User.php(199): craft\web\User->renewAuthStatus()
#25 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/yiisoft/yii2/base/Component.php(139): yii\web\User->getIdentity()
#26 /Users/cornelius/Git/@mostlyserious/coxhealth/config/environment-label.php(7): yii\base\Component->__get('identity')
#27 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/craftcms/cms/src/services/Config.php(289): include('/Users/corneliu...')
#28 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/craftcms/cms/src/services/Config.php(281): craft\services\Config->_configFromFileInternal('/Users/corneliu...')
#29 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/craftcms/cms/src/services/Plugins.php(934): craft\services\Config->getConfigFromFile('environment-lab...')
#30 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/craftcms/cms/src/services/Plugins.php(228): craft\services\Plugins->createPlugin('environment-lab...', Array)
#31 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/craftcms/cms/src/base/ApplicationTrait.php(1497): craft\services\Plugins->loadPlugins()
#32 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/craftcms/cms/src/web/Application.php(105): craft\web\Application->_postInit()
#33 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#34 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct(Array)
#35 [internal function]: yii\base\Application->__construct(Array)
#36 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#37 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#38 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#39 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/craftcms/cms/src/Craft.php(53): yii\BaseYii::createObject(Array, Array)
#40 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/craftcms/cms/bootstrap/bootstrap.php(252): Craft::createObject(Array)
#41 /Users/cornelius/Git/@mostlyserious/coxhealth/vendor/craftcms/cms/bootstrap/web.php(40): require('/Users/corneliu...')
#42 /Users/cornelius/Git/@mostlyserious/coxhealth/web/index.php(11): require('/Users/corneliu...')
#43 /Users/cornelius/.composer/vendor/laravel/valet/server.php(235): require('/Users/corneliu...')
#44 {main}
```

**Comment by engram-design** [comment]
@corneliusio Fixed for the next release. To get this early run `composer require verbb/hyper:"dev-craft-4 as 1.0.5.2"`

**Comment by corneliusio** [comment]
@engram-design That fixed the PHP error for me. However, I can no longer disable specific link types and the field UI does not appear on the entry pages. There are no errors in the console to indicate a JS error.

**Comment by engram-design** [comment]
What happens when you try to disable specific link types? Does the lightswitch actually toggle off? And just when you save the field it switches back to what it was?

As for the field input for the entry, are you able to inspect the HTML source to see what should be here:

![CleanShot 2023-03-02 at 09 10 36@2x](https://user-images.githubusercontent.com/1221575/222276688-e9194599-b8d1-4d5f-9cfc-972d39efc0ab.png)

**Comment by corneliusio** [comment]
The toggles do toggle off but revert back when the field is saved. 

This is all there is where the field should be:
<img width="430" alt="Screenshot 2023-03-01 at 5 05 11 PM" src="https://user-images.githubusercontent.com/4140885/222298136-543400ef-db49-41c5-a3d5-b19038392295.png">

**Comment by engram-design** [comment]
Sounds like something is amiss with the JavaScript for some reason, although it certainly looks like it's initializing Vue and the component, it's just empty. I'm not _quite_ sure what's going on.

**Comment by engram-design** [comment]
Updated in [1.1.0](https://github.com/verbb/hyper/releases/tag/1.1.0) @corneliusio I might recommend opening up a new issue, as your latest one seems different to the original issue.

**Comment by corneliusio** [comment]
@engram-design Sounds good, I'll get updated and if it continues to occur will see if I can find any other factors that may contribute to what I'm seeing.
